description: 'ResNet CIFAR10'
output_dir: $SCRATCH/sc18-dl-tutorial/cifar10-resnet-N${SLURM_JOB_NUM_NODES}-${SLURM_JOB_ID}

data:
    name: cifar10

model:
    name: resnet_small
    input_shape: [32, 32, 3]
    n_classes: 10

optimizer:
    name: Adam
    lr: 0.0001
    lr_scaling: linear

training:
    batch_size: 64
    n_epochs: 64
    lr_warmup_epochs: 5
    loss: categorical_crossentropy
    metrics: [accuracy]
    lr_schedule:
        - {start_epoch: 5, end_epoch: 32, multiplier: 1.}
        - {start_epoch: 32, end_epoch: 48, multiplier: 1.e-1}
        - {start_epoch: 48, multiplier: 1.e-2}

device:
    intra_threads: 32
    blocktime: 0
